// Mocks generated by Mockito 5.1.0 from annotations
// in system_maua_front/test/app/modules/mural-divulgacao/mural-equipes/mural_equipes_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:system_maua_front/app/modules/mural-divulgacao/pages/mural_equipes/models/equipes_model.dart'
    as _i4;
import 'package:system_maua_front/app/modules/mural-divulgacao/pages/mural_equipes/repositories/mural_equipes_repository_interface.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [IMuralEquipesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMuralEquipesRepository extends _i1.Mock
    implements _i2.IMuralEquipesRepository {
  MockIMuralEquipesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.EquipesModel>> getEquipes() =>
      (super.noSuchMethod(Invocation.method(#getEquipes, []),
              returnValue:
                  Future<List<_i4.EquipesModel>>.value(<_i4.EquipesModel>[]))
          as _i3.Future<List<_i4.EquipesModel>>);
}
