// Mocks generated by Mockito 5.0.16 from annotations
// in system_maua_front/test/app/modules/notas/atividades/atividades_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:system_maua_front/app/modules/notas/pages/atividades/models/atividade_model.dart'
    as _i4;
import 'package:system_maua_front/app/modules/notas/pages/atividades/repositories/atividades_repository_interface.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [IAtividadesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAtividadesRepository extends _i1.Mock
    implements _i2.IAtividadesRepository {
  MockIAtividadesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AtividadeModel>> getAtividades() => (super.noSuchMethod(
          Invocation.method(#getAtividades, []),
          returnValue:
              Future<List<_i4.AtividadeModel>>.value(<_i4.AtividadeModel>[]))
      as _i3.Future<List<_i4.AtividadeModel>>);
  @override
  String toString() => super.toString();
}
