// Mocks generated by Mockito 5.1.0 from annotations
// in system_maua_front/test/app/modules/home/home_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:system_maua_front/app/modules/home/repositories/home_repository_interface.dart'
    as _i3;
import 'package:system_maua_front/app/shared/models/classes_model.dart' as _i5;
import 'package:system_maua_front/app/shared/models/student_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeStudentModel_0 extends _i1.Fake implements _i2.StudentModel {}

/// A class which mocks [IHomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHomeRepository extends _i1.Mock implements _i3.IHomeRepository {
  MockIHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.StudentModel> getUser() => (super.noSuchMethod(
          Invocation.method(#getUser, []),
          returnValue: Future<_i2.StudentModel>.value(_FakeStudentModel_0()))
      as _i4.Future<_i2.StudentModel>);
  @override
  _i4.Future<List<_i5.ClassesModel>> getClass() =>
      (super.noSuchMethod(Invocation.method(#getClass, []),
              returnValue:
                  Future<List<_i5.ClassesModel>>.value(<_i5.ClassesModel>[]))
          as _i4.Future<List<_i5.ClassesModel>>);
}
