// Mocks generated by Mockito 5.0.15 from annotations
// in system_maua_front/test/app/modules/home_aluno/home_aluno_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:system_maua_front/app/modules/home-aluno/repositories/home_aluno_repository_interface.dart'
    as _i4;
import 'package:system_maua_front/app/shared/models/aluno_model.dart' as _i2;
import 'package:system_maua_front/app/shared/models/aula_model.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeAlunoModel_0 extends _i1.Fake implements _i2.AlunoModel {}

class _FakeAulaModel_1 extends _i1.Fake implements _i3.AulaModel {}

/// A class which mocks [IHomeAlunoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHomeAlunoRepository extends _i1.Mock
    implements _i4.IHomeAlunoRepository {
  MockIHomeAlunoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AlunoModel> getAluno() =>
      (super.noSuchMethod(Invocation.method(#getAluno, []),
              returnValue: Future<_i2.AlunoModel>.value(_FakeAlunoModel_0()))
          as _i5.Future<_i2.AlunoModel>);
  @override
  _i5.Future<_i3.AulaModel> getAula() =>
      (super.noSuchMethod(Invocation.method(#getAula, []),
              returnValue: Future<_i3.AulaModel>.value(_FakeAulaModel_1()))
          as _i5.Future<_i3.AulaModel>);
  @override
  String toString() => super.toString();
}
