// Mocks generated by Mockito 5.0.10 from annotations
// in system_maua_front/test/app/modules/calendario/calendario_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:system_maua_front/app/modules/calendario/models/avaliacao_model.dart'
    as _i4;
import 'package:system_maua_front/app/modules/calendario/repositories/calendario_repository_interface.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ICalendarioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockICalendarioRepository extends _i1.Mock
    implements _i2.ICalendarioRepository {
  MockICalendarioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AvaliacaoModel>> getAvaliacoes() => (super.noSuchMethod(
          Invocation.method(#getAvaliacoes, []),
          returnValue:
              Future<List<_i4.AvaliacaoModel>>.value(<_i4.AvaliacaoModel>[]))
      as _i3.Future<List<_i4.AvaliacaoModel>>);
}
