// Mocks generated by Mockito 5.0.10 from annotations
// in system_maua_front/test/app/modules/materias/materias_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:system_maua_front/app/modules/materias/models/materias_model.dart'
    as _i3;
import 'package:system_maua_front/app/modules/materias/models/professores_model.dart'
    as _i6;
import 'package:system_maua_front/app/modules/materias/pages/materias-aulas/models/materias_aulas_model.dart'
    as _i2;
import 'package:system_maua_front/app/modules/materias/repositories/materias_repository_interface.dart'
    as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeMateriasAulasModel extends _i1.Fake
    implements _i2.MateriasAulasModel {}

class _FakeMateriasModel extends _i1.Fake implements _i3.MateriasModel {}

/// A class which mocks [IMateriasRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMateriasRepository extends _i1.Mock
    implements _i4.IMateriasRepository {
  MockIMateriasRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.MateriasModel>> getMaterias() =>
      (super.noSuchMethod(Invocation.method(#getMaterias, []),
              returnValue:
                  Future<List<_i3.MateriasModel>>.value(<_i3.MateriasModel>[]))
          as _i5.Future<List<_i3.MateriasModel>>);
  @override
  _i5.Future<List<_i6.ProfessoresModel>> getProfessores(
          String? codigoMateria) =>
      (super.noSuchMethod(Invocation.method(#getProfessores, [codigoMateria]),
              returnValue: Future<List<_i6.ProfessoresModel>>.value(
                  <_i6.ProfessoresModel>[]))
          as _i5.Future<List<_i6.ProfessoresModel>>);
  @override
  _i5.Future<_i2.MateriasAulasModel> getAula(
          String? codigoMateria, int? idPagina) =>
      (super.noSuchMethod(
              Invocation.method(#getAula, [codigoMateria, idPagina]),
              returnValue: Future<_i2.MateriasAulasModel>.value(
                  _FakeMateriasAulasModel()))
          as _i5.Future<_i2.MateriasAulasModel>);
  @override
  _i5.Future<_i3.MateriasModel> getMateriaEspecifica(String? codigoMateria) =>
      (super.noSuchMethod(
              Invocation.method(#getMateriaEspecifica, [codigoMateria]),
              returnValue:
                  Future<_i3.MateriasModel>.value(_FakeMateriasModel()))
          as _i5.Future<_i3.MateriasModel>);
}
