// Mocks generated by Mockito 5.0.10 from annotations
// in system_maua_front/test/app/modules/mural_divulgacao/mural_divulgacao_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:system_maua_front/app/modules/mural-divulgacao/repositories/mural_divulgacao_repository_interface.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [IMuralDivulgacaoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMuralDivulgacaoRepository extends _i1.Mock
    implements _i2.IMuralDivulgacaoRepository {
  MockIMuralDivulgacaoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> getInformacaoVendasNaoLido() =>
      (super.noSuchMethod(Invocation.method(#getInformacaoVendasNaoLido, []),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
  @override
  _i3.Future<int> getInformacaoEquipesNaoLido() =>
      (super.noSuchMethod(Invocation.method(#getInformacaoEquipesNaoLido, []),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
  @override
  _i3.Future<int> getInformacaoCaNaoLido() =>
      (super.noSuchMethod(Invocation.method(#getInformacaoCaNaoLido, []),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
  @override
  _i3.Future<int> getInformacaoEstagioNaoLido() =>
      (super.noSuchMethod(Invocation.method(#getInformacaoEstagioNaoLido, []),
          returnValue: Future<int>.value(0)) as _i3.Future<int>);
}
