# This is a basic workflow to help you get started with Actions

name: Flutter CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    # branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - uses: jacopo1395/action-autotag@2.0.3
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: flutter pub get
      - run: flutter analyze
      
      # Report:
      - name: Install lcov
        run: sudo apt-get install lcov
      - name: Flutter Test
        run: flutter test --coverage
      - name: Create report
        run: genhtml coverage/lcov.info -o coverage/html     
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: coverage/lcov.info
          flags: unittests # optional
          directory: coverage/
          functionalities: html
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: coverage/html/